# Generated by Django 4.2.5 on 2023-11-07 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_place', '0002_storagebox_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagebox',
            name='monthly_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
            preserve_default=False,
        ),
    ]
